language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"

install:
- pip install numpy
- pip install pyqtgraph
- pip install pyserial

script:
- ./runNeblinaDataTests.sh

notifications:
  slack: motsai:uH6mGa8ZK2RfCrFBncRZmGaX
  email:
    on_success: [change] # default: change
    on_failure: [always] # default: always
